const state = { roots: [], presets: [], jobs: [], capabilities: null, selectedRoot: null, specValid: false };
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
async function api(path, options = {}) { const response = await fetch(path, { headers: {'Content-Type':'application/json', ...(options.headers || {})}, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `请求失败（${response.status}）`); return data; }
async function boot() { bindNavigation(); $('#refresh-button').addEventListener('click', refresh); $('#new-job-button').addEventListener('click', openJobDialog); $('[data-open-new]').addEventListener('click', openJobDialog); document.querySelectorAll('[data-close-job]').forEach((button) => button.addEventListener('click', closeJobDialog)); $('#job-form').addEventListener('submit', submitJob); $('#validate-spec').addEventListener('click', validateSpec); $('#quality-mode').addEventListener('change', () => { $('#two-pass').disabled = $('#quality-mode').value !== 'bitrate'; }); try { [state.roots, state.presets] = await Promise.all([api('/api/v1/storage-roots'), api('/api/v1/presets')]); renderRoots(); renderFormOptions(); await Promise.all([refreshJobs(), refreshCapabilities()]); $('#service-status').textContent = '服务在线'; } catch (error) { $('#service-status').textContent = '服务不可用'; showToast(error.message, true); } }
function bindNavigation() { document.querySelectorAll('.tab').forEach((tab) => tab.addEventListener('click', () => { document.querySelectorAll('.tab').forEach((item) => item.classList.toggle('active', item === tab)); document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active-view', view.dataset.view === tab.dataset.tab)); })); }
async function refresh() { await Promise.all([refreshJobs(), refreshCapabilities(), refreshRoots()]).catch((error) => showToast(error.message, true)); }
async function refreshJobs() { state.jobs = await api('/api/v1/jobs'); const active = state.jobs.filter((job) => ['queued','probing','running','finalizing'].includes(job.status)).length; $('#queue-count').textContent = active; $('#queue-summary').textContent = `${active} 个活动任务`; $('#job-list').innerHTML = state.jobs.length ? state.jobs.map(renderJob).join('') : ''; $('#queue-empty').style.display = state.jobs.length ? 'none' : 'flex'; document.querySelectorAll('[data-cancel]').forEach((button) => button.addEventListener('click', () => cancelJob(button.dataset.cancel))); }
function renderJob(job, index) { const labels = {queued:'等待中',probing:'分析媒体',running:'转码中',finalizing:'正在保存',succeeded:'已完成',failed:'失败',canceled:'已取消',interrupted:'已中断'}; const stateClass = ['failed','canceled','interrupted'].includes(job.status) ? 'failed' : job.status; const percent = Math.round((job.progress || 0) * 100); const canCancel = ['queued','probing'].includes(job.status); return `<article class="job-card"><span class="job-index">${String(index + 1).padStart(2,'0')}</span><div class="job-name"><div class="job-file">${escapeHtml(job.input_path.split('/').pop())}</div><div class="job-path">${escapeHtml(job.input_root)} / ${escapeHtml(job.input_path)}</div></div><div class="job-preset">${escapeHtml(job.preset_id || 'custom')}<small>${escapeHtml(job.spec_json ? '结构化规格' : '')}</small></div><div class="job-state ${stateClass}"><i class="state-dot"></i>${labels[job.status] || escapeHtml(job.status)}</div><div class="job-progress"><div class="progress-track"><div class="progress-fill" style="width:${percent}%"></div></div><span class="progress-value">${percent}%</span>${canCancel ? `<button class="cancel-button" data-cancel="${escapeHtml(job.id)}">取消</button>` : ''}</div></article>`; }
async function cancelJob(id) { try { await api(`/api/v1/jobs/${encodeURIComponent(id)}/cancel`, {method:'POST'}); showToast('任务已取消'); await refreshJobs(); } catch (error) { showToast(error.message, true); } }
async function refreshRoots() { state.roots = await api('/api/v1/storage-roots'); renderRoots(); renderFormOptions(); }
function renderRoots() { const online = state.roots.filter((root) => root.available && root.marker_ok).length; $('#storage-summary').textContent = `${online} / ${state.roots.length} 个在线`; $('#storage-list').innerHTML = state.roots.map((root) => `<button class="storage-card ${root.available && root.marker_ok ? 'available' : 'offline'}" data-root="${escapeHtml(root.id)}"><div class="storage-card-head"><span class="storage-label">${escapeHtml(root.label)}</span><span class="storage-status">${root.available && root.marker_ok ? '在线' : '不可用'}</span></div><div class="storage-path">${escapeHtml(root.path)}</div><div class="storage-meta"><span>${root.read_only ? '只读' : '可读写'}</span><span>${root.marker_ok ? '挂载已确认' : '缺少标记'}</span></div></button>`).join(''); document.querySelectorAll('[data-root]').forEach((button) => button.addEventListener('click', () => browseRoot(button.dataset.root))); }
async function browseRoot(id) { state.selectedRoot = id; const root = state.roots.find((item) => item.id === id); $('#browser-root-label').textContent = root?.label || id; try { const entries = await api(`/api/v1/storage-roots/${encodeURIComponent(id)}/entries?path=`); $('#file-list').innerHTML = entries.length ? entries.map((entry) => `<div class="file-entry"><span>${entry.directory ? '▱' : '□'} ${escapeHtml(entry.name)}</span><small>${entry.directory ? '目录' : formatBytes(entry.size)}</small></div>`).join('') : '<p class="muted">这个目录还是空的。</p>'; } catch (error) { $('#file-list').innerHTML = `<p class="muted">${escapeHtml(error.message)}</p>`; } }
function renderFormOptions() { const options = state.roots.map((root) => `<option value="${escapeHtml(root.id)}">${escapeHtml(root.label)}</option>`).join(''); $('#input-root').innerHTML = options; $('#output-root').innerHTML = options; }
function openJobDialog() { $('#form-error').textContent = ''; $('#spec-summary').textContent = '规格尚未校验'; state.specValid = false; $('#job-dialog').showModal(); }
function closeJobDialog() { $('#job-dialog').close(); }
function valueOrNull(id, parser = (value) => value) { const value = $(`#${id}`).value.trim(); return value === '' ? null : parser(value); }
function buildSpec() { const spec = { version: 1, container: $('#container').value, video: { encoder: $('#video-encoder').value, quality: $('#quality-mode').value, quality_value: Number($('#quality-value').value), speed: $('#video-speed').value, tune: null, profile: null, level: null, framerate: valueOrNull('framerate', Number), framerate_mode: 'vfr', pixel_format: null, two_pass: $('#two-pass').checked }, geometry: { width: valueOrNull('width', Number), height: valueOrNull('height', Number), keep_aspect: $('#keep-aspect').checked, crop: {top:0,bottom:0,left:0,right:0}, rotate: null }, filters: { deinterlace: $('#deinterlace').checked, denoise: $('#denoise').checked ? 'hqdn3d' : null, sharpen: $('#sharpen').checked, grayscale: $('#grayscale').checked }, audio: [{ source: Number($('#audio-source').value), encoder: $('#audio-encoder').value, bitrate_kbps: Number($('#audio-bitrate').value), mixdown: 'stereo', gain_db: 0, delay_ms: 0 }], subtitles: valueOrNull('subtitle-source', Number) === null ? [] : [{ source: Number($('#subtitle-source').value), mode: $('#subtitle-mode').value, forced: false, default: false, language: null, external_path: null }], chapters: { enabled: $('#chapters').checked, names: [] }, metadata: { title: null, comment: null }, range: { start_seconds: null, end_seconds: null } }; return spec; }
async function validateSpec() { const error = $('#form-error'); error.textContent = ''; try { const result = await api('/api/v1/spec/validate', {method:'POST', body: JSON.stringify(buildSpec())}); state.specValid = result.valid; $('#spec-summary').textContent = '✓ 规格有效 · 服务端白名单校验通过'; $('#spec-summary').classList.add('valid'); } catch (requestError) { state.specValid = false; $('#spec-summary').textContent = '规格校验失败'; $('#spec-summary').classList.remove('valid'); error.textContent = requestError.message; } }
async function submitJob(event) { event.preventDefault(); const error = $('#form-error'); error.textContent = ''; const spec = buildSpec(); try { spec.video.quality_value = Number(spec.video.quality_value); const body = { input_root: $('#input-root').value, input_path: $('#input-path').value.trim(), output_root: $('#output-root').value, output_path: $('#output-path').value.trim(), preset_id: 'custom', spec }; await api('/api/v1/jobs', {method:'POST', body: JSON.stringify(body)}); closeJobDialog(); event.target.reset(); showToast('结构化转码任务已加入队列'); document.querySelector('[data-tab="queue"]').click(); await refreshJobs(); } catch (requestError) { error.textContent = requestError.message; } }
async function refreshCapabilities() { try { const [caps, tools] = await Promise.all([api('/api/v1/capabilities'), api('/api/v1/tools')]); state.capabilities = caps; $('#encoder-summary').textContent = caps.ffmpeg_available ? (caps.ffmpeg_version || 'FFmpeg 已就绪').replace(/^ffmpeg version /,'').split(' ')[0] : '未找到 FFmpeg'; renderCapabilities(caps); renderToolInstall(tools); } catch (error) { $('#encoder-summary').textContent = '读取失败'; $('#capability-panel').innerHTML = `<p class="muted">${escapeHtml(error.message)}</p>`; renderToolInstall({state:'failed', error:error.message}); } }
function renderToolInstall(tools) { const labels = {disabled:'安装器已关闭', misconfigured:'安装器配置不完整', not_installed:'尚未安装私有 FFmpeg', installing:'正在安装 FFmpeg', ready:'私有 FFmpeg 已就绪', failed:'安装失败'}; const busy = tools.state === 'installing'; const action = ['not_installed','failed'].includes(tools.state) ? `<button class="primary-button" id="install-tools" ${busy ? 'disabled' : ''}>${tools.state === 'failed' ? '重试安装' : '一键安装 FFmpeg'}</button>` : ''; $('#tool-install-panel').innerHTML = `<div class="tool-install-copy"><p class="eyebrow">PRIVATE RUNTIME</p><strong>${labels[tools.state] || 'FFmpeg 状态未知'}</strong><span>${escapeHtml(tools.version ? `固定 bundle · ${tools.version}` : (tools.error || '仅使用应用私有目录，不修改 Ubuntu'))}</span></div><div class="tool-install-action">${busy ? `<progress max="100" value="${tools.progress || 0}"></progress><small>${tools.progress || 0}%</small>` : action}</div>`; $('#install-tools')?.addEventListener('click', installTools); }
async function installTools() { const button = $('#install-tools'); if (button) button.disabled = true; try { await api('/api/v1/tools', {method:'POST', body:'{}'}); showToast('已开始安装 FFmpeg'); await refreshCapabilities(); } catch (error) { showToast(error.message, true); await refreshCapabilities(); } }
function renderCapabilities(caps) { const encoders = (caps.encoders || []).filter((name) => /264|265|av1|vp9|nvenc|vaapi|qsv/.test(name)).slice(0, 30); $('#capability-panel').innerHTML = `<div class="cap-block"><div class="cap-label">FFMPEG RUNTIME</div><div class="cap-value ${caps.ffmpeg_available ? 'good' : ''}">${caps.ffmpeg_available ? '可用' : '缺失'}</div><div class="cap-detail">${escapeHtml(caps.ffmpeg_version || '未检测到 ffmpeg')}<br>${caps.ffprobe_available ? 'ffprobe · 可用' : 'ffprobe · 缺失'}</div></div><div class="cap-block"><div class="cap-label">VIDEO ENCODERS</div><div class="chip-list">${encoders.length ? encoders.map((name) => `<span class="chip">${escapeHtml(name)}</span>`).join('') : '<span class="muted">暂无数据</span>'}</div></div><div class="cap-block"><div class="cap-label">HARDWARE PATHS</div><div class="chip-list">${(caps.hardware_acceleration || []).length ? caps.hardware_acceleration.map((name) => `<span class="chip">${escapeHtml(name)}</span>`).join('') : '<span class="muted">未透传硬件设备</span>'}</div></div>`; }
function formatBytes(bytes) { if (!bytes) return '0 B'; const units = ['B','KB','MB','GB','TB']; const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}`; }
function showToast(message, danger = false) { const toast = $('#toast'); toast.textContent = message; toast.style.background = danger ? 'var(--red)' : 'var(--amber)'; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
boot(); setInterval(() => { if (document.visibilityState === 'visible') refreshJobs().catch(() => {}); }, 3000);
